- name: Start Catalogue Container
  docker_container:
    name: catalogue
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/catalogue
    state: started
    restart: yes
    ports:
     - "8080:8080"
    env:
        MONGO: "true"
        MONGO_URL: "mongodb://mongo.{{env}}.{{dns_domain}}:27017/catalogue"

- name: Load Catalogue Master Data
  docker_container:
    name: master-data
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
    state: started
    env:
        DB_TYPE: "mongo"
        APP_GIT_URL: https://github.com/roboshop-devops-project-v3/catalogue
        DB_HOST: mongo.{{env}}.{{dns_domain}}
        SCHEMA_FILE: db/master-data.js


