- name: Start Cart Container
  docker_container:
    name: cart
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/cart
    state: started
    restart: yes
    ports:
     - "8080:8080"
    env:
        CATALOGUE_HOST: catalogue.{{env}}.{{dns_domain}}
        CATALOGUE_PORT: 8080
        REDIS_HOST: redis.{{env}}.{{dns_domain}}


